job.name = USER_EVENTS_WINDOWING_JOB

flink.checkpoint.storage = s3://dummy-event-bucket-stage/flink/checkpoints-zstd
flink.checkpoint.interval = 300000

flink.window.size = 600
flink.window.allowed-lateness = 300
flink.window.idleness = 600

flink.source.kafka.bootstrap.servers = localhost:9092
flink.source.kafka.topic = user_click_events
flink.source.kafka.group = campaign_flink_snappy
flink.sink.path = s3://dummy-event-bucket-stage/flink-zstd/